### ISSUE TITLE
Result of the visual review

### ISSUE THREAD

**Issue by joshuatai** [trendmicro-frontend/react-loader#1]
Hi Cheton,

With respect to the visual review, the vertical alignment of a loader with button could be middle. Then it shouldn't impact a button height (Button height should be 32px).

Current:
![image](https://cloud.githubusercontent.com/assets/1780412/23602902/a7689640-028d-11e7-982f-2eca4639b09d.png)

Recommand:
![image](https://cloud.githubusercontent.com/assets/1780412/23603507/81fc2270-0290-11e7-9cfe-3d4fd40451dc.png)

**Comment by tinaClin** [comment]
Fixed in https://github.com/trendmicro-frontend/react-buttons/commit/466ff537ed2ba08cddba91da8b6e531847eed865
